services:
  runner:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - RUNNER_ARCH=${RUNNER_ARCH:-x64}
    image: dannyfranca/github-runner:latest
    platform: linux/amd64
    restart: unless-stopped
    environment:
      - REPOSITORY=${REPOSITORY}
      - RUNNER_LABELS=${RUNNER_LABELS:-docker}
      - ACCESS_TOKEN=${ACCESS_TOKEN}
      - RUNNER_TYPE=${RUNNER_TYPE:-org}
      - RUNNER_NAME_PREFIX=${RUNNER_NAME_PREFIX:-runner}
    stop_signal: SIGTERM
    stop_grace_period: 30s
    labels:
      - "com.github.runner.repository=${REPOSITORY}"
      - "com.github.runner.type=${RUNNER_TYPE:-org}"
      - "com.github.runner.labels=${RUNNER_LABELS:-docker}"
      - "com.github.runner.prefix=${RUNNER_NAME_PREFIX:-runner}"
